// Mocks generated by Mockito 5.4.4 from annotations
// in gn_mobile_monitoring/test/presentation/viewmodel/map_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gn_mobile_monitoring/domain/model/site_complement.dart' as _i6;
import 'package:gn_mobile_monitoring/domain/usecase/get_site_complements_use_case.dart'
    as _i5;
import 'package:gn_mobile_monitoring/domain/usecase/get_user_location_use_case.dart'
    as _i4;
import 'package:gn_mobile_monitoring/domain/usecase/load_map_tile_layers_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoadMapTileLayersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadMapTileLayersUseCase extends _i1.Mock
    implements _i2.LoadMapTileLayersUseCase {
  MockLoadMapTileLayersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.TileLayerConfig>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i3.Future<List<_i2.TileLayerConfig>>.value(
            <_i2.TileLayerConfig>[]),
      ) as _i3.Future<List<_i2.TileLayerConfig>>);
}

/// A class which mocks [GetUserLocationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserLocationUseCase extends _i1.Mock
    implements _i4.GetUserLocationUseCase {
  MockGetUserLocationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserLocationResult?> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i3.Future<_i4.UserLocationResult?>.value(),
      ) as _i3.Future<_i4.UserLocationResult?>);

  @override
  _i3.Stream<_i4.UserLocationResult> watchPosition() => (super.noSuchMethod(
        Invocation.method(
          #watchPosition,
          [],
        ),
        returnValue: _i3.Stream<_i4.UserLocationResult>.empty(),
      ) as _i3.Stream<_i4.UserLocationResult>);

  @override
  _i3.Future<bool> isLocationAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isLocationAvailable,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [GetSiteComplementsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSiteComplementsUseCase extends _i1.Mock
    implements _i5.GetSiteComplementsUseCase {
  MockGetSiteComplementsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.SiteComplement>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.SiteComplement>>.value(<_i6.SiteComplement>[]),
      ) as _i3.Future<List<_i6.SiteComplement>>);

  @override
  _i3.Future<Map<int, _i6.SiteComplement?>> executeForSites(
          List<int>? siteIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeForSites,
          [siteIds],
        ),
        returnValue: _i3.Future<Map<int, _i6.SiteComplement?>>.value(
            <int, _i6.SiteComplement?>{}),
      ) as _i3.Future<Map<int, _i6.SiteComplement?>>);

  @override
  _i3.Future<_i6.SiteComplement?> executeForSite(int? siteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeForSite,
          [siteId],
        ),
        returnValue: _i3.Future<_i6.SiteComplement?>.value(),
      ) as _i3.Future<_i6.SiteComplement?>);
}
