// Mocks generated by Mockito 5.4.4 from annotations
// in gn_mobile_monitoring/test/data/repository/visites_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gn_mobile_monitoring/data/datasource/interface/database/modules_database.dart'
    as _i11;
import 'package:gn_mobile_monitoring/data/datasource/interface/database/sites_database.dart'
    as _i5;
import 'package:gn_mobile_monitoring/data/datasource/interface/database/visites_database.dart'
    as _i3;
import 'package:gn_mobile_monitoring/domain/model/base_site.dart' as _i6;
import 'package:gn_mobile_monitoring/domain/model/module.dart' as _i2;
import 'package:gn_mobile_monitoring/domain/model/module_complement.dart'
    as _i13;
import 'package:gn_mobile_monitoring/domain/model/site_complement.dart' as _i7;
import 'package:gn_mobile_monitoring/domain/model/site_group.dart' as _i8;
import 'package:gn_mobile_monitoring/domain/model/site_module.dart' as _i10;
import 'package:gn_mobile_monitoring/domain/model/sites_group_module.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeModule_0 extends _i1.SmartFake implements _i2.Module {
  _FakeModule_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VisitesDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisitesDatabase extends _i1.Mock implements _i3.VisitesDatabase {
  @override
  _i4.Future<List<dynamic>> getAllVisits() => (super.noSuchMethod(
        Invocation.method(
          #getAllVisits,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<List<dynamic>> getVisitsBySiteIdAndModuleId(
    int? siteId,
    int? moduleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVisitsBySiteIdAndModuleId,
          [
            siteId,
            moduleId,
          ],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<dynamic> getVisitById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getVisitById,
          [id],
        ),
        returnValue: _i4.Future<dynamic>.value(),
        returnValueForMissingStub: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<int> insertVisit(dynamic visit) => (super.noSuchMethod(
        Invocation.method(
          #insertVisit,
          [visit],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> updateVisit(dynamic visit) => (super.noSuchMethod(
        Invocation.method(
          #updateVisit,
          [visit],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> deleteVisit(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteVisit,
          [id],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<dynamic> getVisitComplementById(int? visitId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVisitComplementById,
          [visitId],
        ),
        returnValue: _i4.Future<dynamic>.value(),
        returnValueForMissingStub: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<int> insertVisitComplement(dynamic complement) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertVisitComplement,
          [complement],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> updateVisitComplement(dynamic complement) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVisitComplement,
          [complement],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> deleteVisitComplement(int? visitId) => (super.noSuchMethod(
        Invocation.method(
          #deleteVisitComplement,
          [visitId],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> deleteVisitWithComplement(int? visitId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVisitWithComplement,
          [visitId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<dynamic>> getVisitObservers(int? visitId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVisitObservers,
          [visitId],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<int> insertVisitObserver(dynamic observer) => (super.noSuchMethod(
        Invocation.method(
          #insertVisitObserver,
          [observer],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteVisitObservers(int? visitId) => (super.noSuchMethod(
        Invocation.method(
          #deleteVisitObservers,
          [visitId],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> replaceVisitObservers(
    int? visitId,
    List<dynamic>? observers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceVisitObservers,
          [
            visitId,
            observers,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<dynamic>> getVisitsBySite(int? siteId) => (super.noSuchMethod(
        Invocation.method(
          #getVisitsBySite,
          [siteId],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<bool> updateVisitServerId(
    int? localVisitId,
    int? serverId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVisitServerId,
          [
            localVisitId,
            serverId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [SitesDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSitesDatabase extends _i1.Mock implements _i5.SitesDatabase {
  @override
  _i4.Future<void> clearSites() => (super.noSuchMethod(
        Invocation.method(
          #clearSites,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertSites(List<_i6.BaseSite>? sites) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSites,
          [sites],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSite(_i6.BaseSite? site) => (super.noSuchMethod(
        Invocation.method(
          #updateSite,
          [site],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSite(int? siteId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSite,
          [siteId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.BaseSite>> getAllSites() => (super.noSuchMethod(
        Invocation.method(
          #getAllSites,
          [],
        ),
        returnValue: _i4.Future<List<_i6.BaseSite>>.value(<_i6.BaseSite>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.BaseSite>>.value(<_i6.BaseSite>[]),
      ) as _i4.Future<List<_i6.BaseSite>>);

  @override
  _i4.Future<void> clearSiteComplements() => (super.noSuchMethod(
        Invocation.method(
          #clearSiteComplements,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertSiteComplements(
          List<_i7.SiteComplement>? complements) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteComplements,
          [complements],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSiteComplement(int? siteId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSiteComplement,
          [siteId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.SiteComplement>> getAllSiteComplements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSiteComplements,
          [],
        ),
        returnValue:
            _i4.Future<List<_i7.SiteComplement>>.value(<_i7.SiteComplement>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.SiteComplement>>.value(<_i7.SiteComplement>[]),
      ) as _i4.Future<List<_i7.SiteComplement>>);

  @override
  _i4.Future<List<_i7.SiteComplement>> getSiteComplementsByModuleId(
          int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteComplementsByModuleId,
          [moduleId],
        ),
        returnValue:
            _i4.Future<List<_i7.SiteComplement>>.value(<_i7.SiteComplement>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.SiteComplement>>.value(<_i7.SiteComplement>[]),
      ) as _i4.Future<List<_i7.SiteComplement>>);

  @override
  _i4.Future<bool> siteHasOtherModuleReferences(
    int? siteId,
    int? excludeModuleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #siteHasOtherModuleReferences,
          [
            siteId,
            excludeModuleId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> siteGroupHasOtherModuleReferences(
    int? siteGroupId,
    int? excludeModuleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #siteGroupHasOtherModuleReferences,
          [
            siteGroupId,
            excludeModuleId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> deleteSiteCompletely(int? siteId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSiteCompletely,
          [siteId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearSiteGroups() => (super.noSuchMethod(
        Invocation.method(
          #clearSiteGroups,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertSiteGroups(List<_i8.SiteGroup>? siteGroups) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteGroups,
          [siteGroups],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSiteGroup(_i8.SiteGroup? siteGroup) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSiteGroup,
          [siteGroup],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSiteGroup(int? siteGroupId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSiteGroup,
          [siteGroupId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.SiteGroup>> getAllSiteGroups() => (super.noSuchMethod(
        Invocation.method(
          #getAllSiteGroups,
          [],
        ),
        returnValue: _i4.Future<List<_i8.SiteGroup>>.value(<_i8.SiteGroup>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i8.SiteGroup>>.value(<_i8.SiteGroup>[]),
      ) as _i4.Future<List<_i8.SiteGroup>>);

  @override
  _i4.Future<List<_i6.BaseSite>> getSitesForModule(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSitesForModule,
          [moduleId],
        ),
        returnValue: _i4.Future<List<_i6.BaseSite>>.value(<_i6.BaseSite>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.BaseSite>>.value(<_i6.BaseSite>[]),
      ) as _i4.Future<List<_i6.BaseSite>>);

  @override
  _i4.Future<List<_i8.SiteGroup>> getSiteGroupsForModule(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteGroupsForModule,
          [moduleId],
        ),
        returnValue: _i4.Future<List<_i8.SiteGroup>>.value(<_i8.SiteGroup>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i8.SiteGroup>>.value(<_i8.SiteGroup>[]),
      ) as _i4.Future<List<_i8.SiteGroup>>);

  @override
  _i4.Future<void> clearAllSiteGroupModules() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSiteGroupModules,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertSiteGroupModules(
          List<_i9.SitesGroupModule>? modules) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteGroupModules,
          [modules],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSiteGroupModule(
    int? siteGroupId,
    int? moduleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSiteGroupModule,
          [
            siteGroupId,
            moduleId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.SitesGroupModule>> getAllSiteGroupModules() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSiteGroupModules,
          [],
        ),
        returnValue: _i4.Future<List<_i9.SitesGroupModule>>.value(
            <_i9.SitesGroupModule>[]),
        returnValueForMissingStub: _i4.Future<List<_i9.SitesGroupModule>>.value(
            <_i9.SitesGroupModule>[]),
      ) as _i4.Future<List<_i9.SitesGroupModule>>);

  @override
  _i4.Future<List<_i8.SiteGroup>> getSiteGroupsByModuleId(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteGroupsByModuleId,
          [moduleId],
        ),
        returnValue: _i4.Future<List<_i8.SiteGroup>>.value(<_i8.SiteGroup>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i8.SiteGroup>>.value(<_i8.SiteGroup>[]),
      ) as _i4.Future<List<_i8.SiteGroup>>);

  @override
  _i4.Future<List<_i9.SitesGroupModule>> getSiteGroupModulesBySiteGroupId(
          int? siteGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteGroupModulesBySiteGroupId,
          [siteGroupId],
        ),
        returnValue: _i4.Future<List<_i9.SitesGroupModule>>.value(
            <_i9.SitesGroupModule>[]),
        returnValueForMissingStub: _i4.Future<List<_i9.SitesGroupModule>>.value(
            <_i9.SitesGroupModule>[]),
      ) as _i4.Future<List<_i9.SitesGroupModule>>);

  @override
  _i4.Future<void> clearAllSiteModules() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSiteModules,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertSiteModules(List<_i10.SiteModule>? modules) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteModules,
          [modules],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSiteModule(
    int? siteId,
    int? moduleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSiteModule,
          [
            siteId,
            moduleId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.SiteModule>> getAllSiteModules() => (super.noSuchMethod(
        Invocation.method(
          #getAllSiteModules,
          [],
        ),
        returnValue:
            _i4.Future<List<_i10.SiteModule>>.value(<_i10.SiteModule>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i10.SiteModule>>.value(<_i10.SiteModule>[]),
      ) as _i4.Future<List<_i10.SiteModule>>);

  @override
  _i4.Future<List<_i6.BaseSite>> getSitesByModuleId(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSitesByModuleId,
          [moduleId],
        ),
        returnValue: _i4.Future<List<_i6.BaseSite>>.value(<_i6.BaseSite>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.BaseSite>>.value(<_i6.BaseSite>[]),
      ) as _i4.Future<List<_i6.BaseSite>>);

  @override
  _i4.Future<List<_i10.SiteModule>> getSiteModulesBySiteId(int? siteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteModulesBySiteId,
          [siteId],
        ),
        returnValue:
            _i4.Future<List<_i10.SiteModule>>.value(<_i10.SiteModule>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i10.SiteModule>>.value(<_i10.SiteModule>[]),
      ) as _i4.Future<List<_i10.SiteModule>>);

  @override
  _i4.Future<List<_i6.BaseSite>> getSitesBySiteGroup(int? siteGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSitesBySiteGroup,
          [siteGroupId],
        ),
        returnValue: _i4.Future<List<_i6.BaseSite>>.value(<_i6.BaseSite>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.BaseSite>>.value(<_i6.BaseSite>[]),
      ) as _i4.Future<List<_i6.BaseSite>>);

  @override
  _i4.Future<void> insertSite(_i6.BaseSite? site) => (super.noSuchMethod(
        Invocation.method(
          #insertSite,
          [site],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertSiteGroup(_i8.SiteGroup? siteGroup) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteGroup,
          [siteGroup],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.SiteModule>> getSiteModulesByModuleId(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteModulesByModuleId,
          [moduleId],
        ),
        returnValue:
            _i4.Future<List<_i10.SiteModule>>.value(<_i10.SiteModule>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i10.SiteModule>>.value(<_i10.SiteModule>[]),
      ) as _i4.Future<List<_i10.SiteModule>>);

  @override
  _i4.Future<void> insertSiteModule(_i10.SiteModule? siteModule) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteModule,
          [siteModule],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.BaseSite?> getSiteById(int? siteId) => (super.noSuchMethod(
        Invocation.method(
          #getSiteById,
          [siteId],
        ),
        returnValue: _i4.Future<_i6.BaseSite?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.BaseSite?>.value(),
      ) as _i4.Future<_i6.BaseSite?>);
}

/// A class which mocks [ModulesDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockModulesDatabase extends _i1.Mock implements _i11.ModulesDatabase {
  @override
  _i4.Future<void> clearModules() => (super.noSuchMethod(
        Invocation.method(
          #clearModules,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertModules(List<_i2.Module>? modules) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertModules,
          [modules],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateModule(_i2.Module? module) => (super.noSuchMethod(
        Invocation.method(
          #updateModule,
          [module],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Module>> getAllModules() => (super.noSuchMethod(
        Invocation.method(
          #getAllModules,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Module>>.value(<_i2.Module>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Module>>.value(<_i2.Module>[]),
      ) as _i4.Future<List<_i2.Module>>);

  @override
  _i4.Future<String> getModuleCodeFromIdModule(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModuleCodeFromIdModule,
          [moduleId],
        ),
        returnValue: _i4.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getModuleCodeFromIdModule,
            [moduleId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getModuleCodeFromIdModule,
            [moduleId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> markModuleAsDownloaded(int? moduleId) => (super.noSuchMethod(
        Invocation.method(
          #markModuleAsDownloaded,
          [moduleId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertModuleComplements(
          List<_i13.ModuleComplement>? moduleComplements) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertModuleComplements,
          [moduleComplements],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i13.ModuleComplement?> getModuleComplementById(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModuleComplementById,
          [moduleId],
        ),
        returnValue: _i4.Future<_i13.ModuleComplement?>.value(),
        returnValueForMissingStub: _i4.Future<_i13.ModuleComplement?>.value(),
      ) as _i4.Future<_i13.ModuleComplement?>);

  @override
  _i4.Future<_i13.ModuleComplement?> getModuleComplementByModuleCode(
          String? moduleCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModuleComplementByModuleCode,
          [moduleCode],
        ),
        returnValue: _i4.Future<_i13.ModuleComplement?>.value(),
        returnValueForMissingStub: _i4.Future<_i13.ModuleComplement?>.value(),
      ) as _i4.Future<_i13.ModuleComplement?>);

  @override
  _i4.Future<List<_i13.ModuleComplement>> getAllModuleComplements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllModuleComplements,
          [],
        ),
        returnValue: _i4.Future<List<_i13.ModuleComplement>>.value(
            <_i13.ModuleComplement>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i13.ModuleComplement>>.value(
                <_i13.ModuleComplement>[]),
      ) as _i4.Future<List<_i13.ModuleComplement>>);

  @override
  _i4.Future<void> updateModuleComplement(
          _i13.ModuleComplement? moduleComplement) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateModuleComplement,
          [moduleComplement],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateModuleComplementConfiguration(
    int? moduleId,
    String? configuration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateModuleComplementConfiguration,
          [
            moduleId,
            configuration,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteModuleWithComplement(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteModuleWithComplement,
          [moduleId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCorSiteModules(int? moduleId) => (super.noSuchMethod(
        Invocation.method(
          #clearCorSiteModules,
          [moduleId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearSitesGroupModules(int? moduleId) => (super.noSuchMethod(
        Invocation.method(
          #clearSitesGroupModules,
          [moduleId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertSitesGroupModules(
          List<_i9.SitesGroupModule>? siteGroups) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSitesGroupModules,
          [siteGroups],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> associateModuleWithDataset(
    int? moduleId,
    int? datasetId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #associateModuleWithDataset,
          [
            moduleId,
            datasetId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<int>> getDatasetIdsForModule(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDatasetIdsForModule,
          [moduleId],
        ),
        returnValue: _i4.Future<List<int>>.value(<int>[]),
        returnValueForMissingStub: _i4.Future<List<int>>.value(<int>[]),
      ) as _i4.Future<List<int>>);

  @override
  _i4.Future<int?> getModuleTaxonomyListId(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModuleTaxonomyListId,
          [moduleId],
        ),
        returnValue: _i4.Future<int?>.value(),
        returnValueForMissingStub: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<List<_i2.Module>> getModules() => (super.noSuchMethod(
        Invocation.method(
          #getModules,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Module>>.value(<_i2.Module>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Module>>.value(<_i2.Module>[]),
      ) as _i4.Future<List<_i2.Module>>);

  @override
  _i4.Future<_i2.Module?> getModuleById(int? moduleId) => (super.noSuchMethod(
        Invocation.method(
          #getModuleById,
          [moduleId],
        ),
        returnValue: _i4.Future<_i2.Module?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.Module?>.value(),
      ) as _i4.Future<_i2.Module?>);

  @override
  _i4.Future<_i2.Module> getModuleWithRelationsById(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModuleWithRelationsById,
          [moduleId],
        ),
        returnValue: _i4.Future<_i2.Module>.value(_FakeModule_0(
          this,
          Invocation.method(
            #getModuleWithRelationsById,
            [moduleId],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Module>.value(_FakeModule_0(
          this,
          Invocation.method(
            #getModuleWithRelationsById,
            [moduleId],
          ),
        )),
      ) as _i4.Future<_i2.Module>);

  @override
  _i4.Future<List<_i2.Module>> getDownloadedModules() => (super.noSuchMethod(
        Invocation.method(
          #getDownloadedModules,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Module>>.value(<_i2.Module>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Module>>.value(<_i2.Module>[]),
      ) as _i4.Future<List<_i2.Module>>);

  @override
  _i4.Future<_i2.Module?> getModuleIdByLabel(String? moduleLabel) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModuleIdByLabel,
          [moduleLabel],
        ),
        returnValue: _i4.Future<_i2.Module?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.Module?>.value(),
      ) as _i4.Future<_i2.Module?>);

  @override
  _i4.Future<_i2.Module?> getModuleByCode(String? moduleCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModuleByCode,
          [moduleCode],
        ),
        returnValue: _i4.Future<_i2.Module?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.Module?>.value(),
      ) as _i4.Future<_i2.Module?>);
}
