/// Inline fixture data for E2E tests.
///
/// On Android, `dart:io File` cannot read project files at runtime.
/// This file contains all fixture data as Dart constants so they work
/// on any platform (Android emulator, desktop, CI).
class FixtureData {
  static const Map<String, dynamic> fixtures = {
    'auth/login_success.json': {
      'user': {
        'id_role': 1,
        'identifiant': 'testuser',
        'nom_role': 'Test',
        'prenom_role': 'User',
        'nom_complet': 'Test User',
        'id_organisme': 1,
        'email': 'test@geonature.test',
        'active': true,
        'groupe': false,
        'date_insert': '2024-01-01T00:00:00.000Z',
        'date_update': '2024-01-01T00:00:00.000Z',
        'max_level_profil': 6,
        'desc_role': null,
      },
      'token': 'mock-jwt-token-for-e2e-testing',
      'expires': '2099-12-31T23:59:59.000Z',
    },
    'auth/login_failure.json': {
      'type': 'login_error',
      'msg': 'Identifiant ou mot de passe incorrect',
    },
    'modules/modules_list.json': [
      {
        'id_module': 101,
        'module_code': 'TEST_MODULE_1',
        'module_label': 'Module de test 1',
        'module_picto': 'fa-leaf',
        'module_desc': 'Premier module de test pour les E2E',
        'module_group': null,
        'module_path': 'test_module_1',
        'module_external_url': null,
        'module_target': null,
        'module_comment': null,
        'active_frontend': true,
        'active_backend': true,
        'module_doc_url': null,
        'module_order': 1,
        'ng_module': null,
        'meta_create_date': '2024-01-01T00:00:00.000Z',
        'meta_update_date': '2024-01-01T00:00:00.000Z',
        'cruved': {'C': 1, 'R': 2, 'U': 1, 'V': 2, 'E': 0, 'D': 0},
        'uuid_module_complement': 'uuid-comp-101',
        'id_list_observer': 1,
        'id_list_taxonomy': 100,
        'b_synthese': false,
        'taxonomy_display_field_name': 'nom_complet',
        'b_draw_sites_group': false,
        'data': null,
        'configuration': null,
      },
      {
        'id_module': 102,
        'module_code': 'TEST_MODULE_2',
        'module_label': 'Module de test 2',
        'module_picto': 'fa-binoculars',
        'module_desc': 'Deuxième module pour les tests E2E',
        'module_group': null,
        'module_path': 'test_module_2',
        'module_external_url': null,
        'module_target': null,
        'module_comment': null,
        'active_frontend': true,
        'active_backend': true,
        'module_doc_url': null,
        'module_order': 2,
        'ng_module': null,
        'meta_create_date': '2024-01-01T00:00:00.000Z',
        'meta_update_date': '2024-01-01T00:00:00.000Z',
        'cruved': {'C': 1, 'R': 2, 'U': 1, 'V': 2, 'E': 0, 'D': 0},
        'uuid_module_complement': 'uuid-comp-102',
        'id_list_observer': 1,
        'id_list_taxonomy': 100,
        'b_synthese': false,
        'taxonomy_display_field_name': 'nom_complet',
        'b_draw_sites_group': false,
        'data': null,
        'configuration': null,
      },
    ],
    'modules/module_config.json': {
      'module': {
        'label': 'Module de test',
        'children_types': ['site'],
        'display_properties': ['module_label', 'module_desc'],
        'display_list': ['module_label'],
      },
      'site': {
        'label': 'Site',
        'label_list': 'Sites',
        'generic': {
          'base_site_name': {
            'type_widget': 'text',
            'attribut_label': 'Nom du site',
            'required': true,
          },
          'base_site_code': {
            'type_widget': 'text',
            'attribut_label': 'Code du site',
            'required': true,
          },
        },
        'specific': {},
        'display_properties': ['base_site_name', 'base_site_code'],
        'display_list': ['base_site_name', 'base_site_code'],
      },
      'visit': {
        'label': 'Visite',
        'label_list': 'Visites',
        'generic': {
          'visit_date_min': {
            'type_widget': 'date',
            'attribut_label': 'Date',
            'required': true,
          },
          'comments': {
            'type_widget': 'textarea',
            'attribut_label': 'Commentaires',
            'required': false,
          },
        },
        'specific': {},
        'display_properties': ['visit_date_min', 'comments'],
        'display_list': ['visit_date_min', 'comments'],
      },
      'observation': {
        'label': 'Observation',
        'label_list': 'Observations',
        'generic': {
          'cd_nom': {
            'type_widget': 'taxonomy',
            'attribut_label': 'Taxon',
            'required': true,
          },
          'comments': {
            'type_widget': 'textarea',
            'attribut_label': 'Commentaires',
            'required': false,
          },
        },
        'specific': {},
        'display_properties': ['cd_nom', 'comments'],
        'display_list': ['cd_nom', 'comments'],
      },
      'custom': {},
    },
    'sites/sites_enriched.json': [
      {
        'id_base_site': 1,
        'id_module': 101,
        'base_site_name': 'Site de test Alpha',
        'base_site_code': 'SITE_ALPHA',
        'base_site_description': 'Premier site de test',
        'first_use_date': '2024-01-15',
        'last_visit': '2024-06-15',
        'nb_visits': 3,
        'altitude_min': 100,
        'altitude_max': 200,
        'geom': '{"type": "Point", "coordinates": [5.0, 45.0]}',
      },
      {
        'id_base_site': 2,
        'id_module': 101,
        'base_site_name': 'Site de test Beta',
        'base_site_code': 'SITE_BETA',
        'base_site_description': 'Deuxième site de test',
        'first_use_date': '2024-02-01',
        'last_visit': null,
        'nb_visits': 0,
        'altitude_min': 300,
        'altitude_max': 400,
        'geom': '{"type": "Point", "coordinates": [5.1, 45.1]}',
      },
    ],
    'sites/site_create_response.json': {
      'id_base_site': 99,
      'id_module': 101,
      'base_site_name': 'Nouveau site',
      'base_site_code': 'NEW_SITE',
      'base_site_description': 'Site créé par test E2E',
      'first_use_date': null,
      'last_visit': null,
      'nb_visits': 0,
      'altitude_min': null,
      'altitude_max': null,
      'geom': '{"type": "Point", "coordinates": [5.2, 45.2]}',
    },
    'visits/visit_create_response.json': {
      'id_base_visit': 501,
      'id_base_site': 1,
      'id_module': 101,
      'id_dataset': 1,
      'visit_date_min': '2024-06-20',
      'visit_date_max': null,
      'comments': 'Visite créée par test E2E',
      'id_digitiser': 1,
    },
    'observations/observation_create_response.json': {
      'id_observation': 1001,
      'id_base_visit': 501,
      'cd_nom': 67111,
      'comments': 'Observation créée par test E2E',
      'uuid_observation': 'uuid-obs-1001',
    },
    'nomenclatures/nomenclatures.json': [
      {
        'id_type': 1,
        'mnemonique': 'TYP_GRP',
        'label_default': 'Type de groupement',
        'nomenclatures': [
          {
            'id_nomenclature': 101,
            'cd_nomenclature': 'GRP1',
            'label_default': 'Groupe 1',
            'mnemonique': 'GRP1',
          },
          {
            'id_nomenclature': 102,
            'cd_nomenclature': 'GRP2',
            'label_default': 'Groupe 2',
            'mnemonique': 'GRP2',
          },
        ],
      },
      {
        'id_type': 2,
        'mnemonique': 'STATUT_BIO',
        'label_default': 'Statut biologique',
        'nomenclatures': [
          {
            'id_nomenclature': 201,
            'cd_nomenclature': '1',
            'label_default': 'Non renseigné',
            'mnemonique': 'NSP',
          },
          {
            'id_nomenclature': 202,
            'cd_nomenclature': '2',
            'label_default': 'Observé',
            'mnemonique': 'OBS',
          },
        ],
      },
    ],
    'taxons/taxon_list.json': [
      {
        'cd_nom': 67111,
        'cd_ref': 67111,
        'nom_complet': 'Parus major Linnaeus, 1758',
        'nom_vern': 'Mésange charbonnière',
        'lb_nom': 'Parus major',
        'id_rang': 'ES',
        'regne': 'Animalia',
        'group2_inpn': 'Oiseaux',
      },
      {
        'cd_nom': 3120,
        'cd_ref': 3120,
        'nom_complet': 'Bufo bufo (Linnaeus, 1758)',
        'nom_vern': 'Crapaud commun',
        'lb_nom': 'Bufo bufo',
        'id_rang': 'ES',
        'regne': 'Animalia',
        'group2_inpn': 'Amphibiens',
      },
      {
        'cd_nom': 4525,
        'cd_ref': 4525,
        'nom_complet': 'Salamandra salamandra (Linnaeus, 1758)',
        'nom_vern': 'Salamandre tachetée',
        'lb_nom': 'Salamandra salamandra',
        'id_rang': 'ES',
        'regne': 'Animalia',
        'group2_inpn': 'Amphibiens',
      },
    ],
    'taxons/taxon_search.json': [
      {
        'cd_nom': 67111,
        'cd_ref': 67111,
        'nom_complet': 'Parus major Linnaeus, 1758',
        'nom_vern': 'Mésange charbonnière',
        'lb_nom': 'Parus major',
        'id_rang': 'ES',
        'regne': 'Animalia',
        'group2_inpn': 'Oiseaux',
      },
    ],
    'datasets/datasets.json': [
      {
        'id_dataset': 1,
        'dataset_name': 'Jeu de données de test',
        'dataset_shortname': 'JDD_TEST',
        'id_acquisition_framework': 1,
        'active': true,
      },
      {
        'id_dataset': 2,
        'dataset_name': 'Jeu de données secondaire',
        'dataset_shortname': 'JDD_SEC',
        'id_acquisition_framework': 1,
        'active': true,
      },
    ],
  };
}
