// Mocks generated by Mockito 5.4.4 from annotations
// in gn_mobile_monitoring/test/domain/usecase/create_site_with_relations_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gn_mobile_monitoring/data/datasource/interface/database/sites_database.dart'
    as _i5;
import 'package:gn_mobile_monitoring/data/entity/base_site_entity.dart' as _i10;
import 'package:gn_mobile_monitoring/domain/model/base_site.dart' as _i4;
import 'package:gn_mobile_monitoring/domain/model/site_complement.dart' as _i6;
import 'package:gn_mobile_monitoring/domain/model/site_group.dart' as _i7;
import 'package:gn_mobile_monitoring/domain/model/site_module.dart' as _i9;
import 'package:gn_mobile_monitoring/domain/model/sites_group_module.dart'
    as _i8;
import 'package:gn_mobile_monitoring/domain/usecase/create_site_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CreateSiteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateSiteUseCase extends _i1.Mock implements _i2.CreateSiteUseCase {
  MockCreateSiteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> execute(_i4.BaseSite? site) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [site],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [SitesDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSitesDatabase extends _i1.Mock implements _i5.SitesDatabase {
  MockSitesDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> clearSites() => (super.noSuchMethod(
        Invocation.method(
          #clearSites,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertSites(List<_i4.BaseSite>? sites) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSites,
          [sites],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSite(_i4.BaseSite? site) => (super.noSuchMethod(
        Invocation.method(
          #updateSite,
          [site],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSite(int? siteId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSite,
          [siteId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.BaseSite>> getAllSites() => (super.noSuchMethod(
        Invocation.method(
          #getAllSites,
          [],
        ),
        returnValue: _i3.Future<List<_i4.BaseSite>>.value(<_i4.BaseSite>[]),
      ) as _i3.Future<List<_i4.BaseSite>>);

  @override
  _i3.Future<void> clearSiteComplements() => (super.noSuchMethod(
        Invocation.method(
          #clearSiteComplements,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertSiteComplements(
          List<_i6.SiteComplement>? complements) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteComplements,
          [complements],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSiteComplement(int? siteId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSiteComplement,
          [siteId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.SiteComplement>> getAllSiteComplements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSiteComplements,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.SiteComplement>>.value(<_i6.SiteComplement>[]),
      ) as _i3.Future<List<_i6.SiteComplement>>);

  @override
  _i3.Future<List<_i6.SiteComplement>> getSiteComplementsByModuleId(
          int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteComplementsByModuleId,
          [moduleId],
        ),
        returnValue:
            _i3.Future<List<_i6.SiteComplement>>.value(<_i6.SiteComplement>[]),
      ) as _i3.Future<List<_i6.SiteComplement>>);

  @override
  _i3.Future<bool> siteHasOtherModuleReferences(
    int? siteId,
    int? excludeModuleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #siteHasOtherModuleReferences,
          [
            siteId,
            excludeModuleId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> siteGroupHasOtherModuleReferences(
    int? siteGroupId,
    int? excludeModuleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #siteGroupHasOtherModuleReferences,
          [
            siteGroupId,
            excludeModuleId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteSiteCompletely(int? siteId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSiteCompletely,
          [siteId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearSiteGroups() => (super.noSuchMethod(
        Invocation.method(
          #clearSiteGroups,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertSiteGroups(List<_i7.SiteGroup>? siteGroups) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteGroups,
          [siteGroups],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSiteGroup(_i7.SiteGroup? siteGroup) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSiteGroup,
          [siteGroup],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSiteGroup(int? siteGroupId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSiteGroup,
          [siteGroupId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.SiteGroup>> getAllSiteGroups() => (super.noSuchMethod(
        Invocation.method(
          #getAllSiteGroups,
          [],
        ),
        returnValue: _i3.Future<List<_i7.SiteGroup>>.value(<_i7.SiteGroup>[]),
      ) as _i3.Future<List<_i7.SiteGroup>>);

  @override
  _i3.Future<List<_i4.BaseSite>> getSitesForModule(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSitesForModule,
          [moduleId],
        ),
        returnValue: _i3.Future<List<_i4.BaseSite>>.value(<_i4.BaseSite>[]),
      ) as _i3.Future<List<_i4.BaseSite>>);

  @override
  _i3.Future<List<_i7.SiteGroup>> getSiteGroupsForModule(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteGroupsForModule,
          [moduleId],
        ),
        returnValue: _i3.Future<List<_i7.SiteGroup>>.value(<_i7.SiteGroup>[]),
      ) as _i3.Future<List<_i7.SiteGroup>>);

  @override
  _i3.Future<void> clearAllSiteGroupModules() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSiteGroupModules,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertSiteGroupModule(
          _i8.SitesGroupModule? siteGroupModule) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteGroupModule,
          [siteGroupModule],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertSiteGroupModules(
          List<_i8.SitesGroupModule>? modules) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteGroupModules,
          [modules],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSiteGroupModule(
    int? siteGroupId,
    int? moduleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSiteGroupModule,
          [
            siteGroupId,
            moduleId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.SitesGroupModule>> getAllSiteGroupModules() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSiteGroupModules,
          [],
        ),
        returnValue: _i3.Future<List<_i8.SitesGroupModule>>.value(
            <_i8.SitesGroupModule>[]),
      ) as _i3.Future<List<_i8.SitesGroupModule>>);

  @override
  _i3.Future<List<_i7.SiteGroup>> getSiteGroupsByModuleId(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteGroupsByModuleId,
          [moduleId],
        ),
        returnValue: _i3.Future<List<_i7.SiteGroup>>.value(<_i7.SiteGroup>[]),
      ) as _i3.Future<List<_i7.SiteGroup>>);

  @override
  _i3.Future<List<_i8.SitesGroupModule>> getSiteGroupModulesBySiteGroupId(
          int? siteGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteGroupModulesBySiteGroupId,
          [siteGroupId],
        ),
        returnValue: _i3.Future<List<_i8.SitesGroupModule>>.value(
            <_i8.SitesGroupModule>[]),
      ) as _i3.Future<List<_i8.SitesGroupModule>>);

  @override
  _i3.Future<void> clearAllSiteModules() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSiteModules,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> insertSiteModules(List<_i9.SiteModule>? modules) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteModules,
          [modules],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSiteModule(
    int? siteId,
    int? moduleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSiteModule,
          [
            siteId,
            moduleId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.SiteModule>> getAllSiteModules() => (super.noSuchMethod(
        Invocation.method(
          #getAllSiteModules,
          [],
        ),
        returnValue: _i3.Future<List<_i9.SiteModule>>.value(<_i9.SiteModule>[]),
      ) as _i3.Future<List<_i9.SiteModule>>);

  @override
  _i3.Future<List<_i4.BaseSite>> getSitesByModuleId(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSitesByModuleId,
          [moduleId],
        ),
        returnValue: _i3.Future<List<_i4.BaseSite>>.value(<_i4.BaseSite>[]),
      ) as _i3.Future<List<_i4.BaseSite>>);

  @override
  _i3.Future<List<_i9.SiteModule>> getSiteModulesBySiteId(int? siteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteModulesBySiteId,
          [siteId],
        ),
        returnValue: _i3.Future<List<_i9.SiteModule>>.value(<_i9.SiteModule>[]),
      ) as _i3.Future<List<_i9.SiteModule>>);

  @override
  _i3.Future<List<_i4.BaseSite>> getSitesBySiteGroup(int? siteGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSitesBySiteGroup,
          [siteGroupId],
        ),
        returnValue: _i3.Future<List<_i4.BaseSite>>.value(<_i4.BaseSite>[]),
      ) as _i3.Future<List<_i4.BaseSite>>);

  @override
  _i3.Future<List<_i4.BaseSite>> getSitesBySiteGroupAndModule(
    int? siteGroupId,
    int? moduleId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSitesBySiteGroupAndModule,
          [
            siteGroupId,
            moduleId,
          ],
        ),
        returnValue: _i3.Future<List<_i4.BaseSite>>.value(<_i4.BaseSite>[]),
      ) as _i3.Future<List<_i4.BaseSite>>);

  @override
  _i3.Future<int> insertSite(_i4.BaseSite? site) => (super.noSuchMethod(
        Invocation.method(
          #insertSite,
          [site],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> insertSiteGroup(_i7.SiteGroup? siteGroup) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteGroup,
          [siteGroup],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i9.SiteModule>> getSiteModulesByModuleId(int? moduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteModulesByModuleId,
          [moduleId],
        ),
        returnValue: _i3.Future<List<_i9.SiteModule>>.value(<_i9.SiteModule>[]),
      ) as _i3.Future<List<_i9.SiteModule>>);

  @override
  _i3.Future<void> insertSiteModule(_i9.SiteModule? siteModule) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSiteModule,
          [siteModule],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i10.BaseSiteEntity?> getSiteEntityById(int? siteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteEntityById,
          [siteId],
        ),
        returnValue: _i3.Future<_i10.BaseSiteEntity?>.value(),
      ) as _i3.Future<_i10.BaseSiteEntity?>);

  @override
  _i3.Future<_i4.BaseSite?> getSiteById(int? siteId) => (super.noSuchMethod(
        Invocation.method(
          #getSiteById,
          [siteId],
        ),
        returnValue: _i3.Future<_i4.BaseSite?>.value(),
      ) as _i3.Future<_i4.BaseSite?>);

  @override
  _i3.Future<_i7.SiteGroup?> getSiteGroupById(int? siteGroupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteGroupById,
          [siteGroupId],
        ),
        returnValue: _i3.Future<_i7.SiteGroup?>.value(),
      ) as _i3.Future<_i7.SiteGroup?>);

  @override
  _i3.Future<void> updateSiteServerId(
    int? localSiteId,
    int? serverSiteId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSiteServerId,
          [
            localSiteId,
            serverSiteId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSiteGroupServerId(
    int? localSiteGroupId,
    int? serverSiteGroupId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSiteGroupServerId,
          [
            localSiteGroupId,
            serverSiteGroupId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSiteComplementsGroupId(
    int? oldGroupId,
    int? newGroupId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSiteComplementsGroupId,
          [
            oldGroupId,
            newGroupId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.SiteComplement?> getSiteComplementBySiteId(int? siteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSiteComplementBySiteId,
          [siteId],
        ),
        returnValue: _i3.Future<_i6.SiteComplement?>.value(),
      ) as _i3.Future<_i6.SiteComplement?>);
}
