// Mocks generated by Mockito 5.4.4 from annotations
// in gn_mobile_monitoring/test/domain/usecase/sync_sites_to_server_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gn_mobile_monitoring/domain/model/sync_result.dart' as _i2;
import 'package:gn_mobile_monitoring/domain/repository/upstream_sync_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UpstreamSyncRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpstreamSyncRepository extends _i1.Mock
    implements _i3.UpstreamSyncRepository {
  MockUpstreamSyncRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> checkConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<DateTime?> getLastSyncDate(String? entityType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastSyncDate,
          [entityType],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<void> updateLastSyncDate(
    String? entityType,
    DateTime? syncDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastSyncDate,
          [
            entityType,
            syncDate,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SyncResult> syncVisitsToServer(
    String? token,
    String? moduleCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncVisitsToServer,
          [
            token,
            moduleCode,
          ],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncVisitsToServer,
            [
              token,
              moduleCode,
            ],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> syncObservationsToServer(
    String? token,
    String? moduleCode,
    int? visitId, {
    int? serverVisitId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncObservationsToServer,
          [
            token,
            moduleCode,
            visitId,
          ],
          {#serverVisitId: serverVisitId},
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncObservationsToServer,
            [
              token,
              moduleCode,
              visitId,
            ],
            {#serverVisitId: serverVisitId},
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> syncObservationDetailsToServer(
    String? token,
    String? moduleCode,
    int? observationId, {
    int? serverObservationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncObservationDetailsToServer,
          [
            token,
            moduleCode,
            observationId,
          ],
          {#serverObservationId: serverObservationId},
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncObservationDetailsToServer,
            [
              token,
              moduleCode,
              observationId,
            ],
            {#serverObservationId: serverObservationId},
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<_i2.SyncResult> syncSitesToServer(
    String? token,
    String? moduleCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncSitesToServer,
          [
            token,
            moduleCode,
          ],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncSitesToServer,
            [
              token,
              moduleCode,
            ],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);
}
